---
title: "tutorial-MPRAbase"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tutorial-MPRAbase}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(MPRAbase)
library(synapser)
```

```{r}
# Login to Synapse with apblair authentication token
synLogin(authToken="eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IlJTMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIl0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC5wcm9kLnNhZ2ViYXNlLm9yZy9hdXRoL3YxIiwiYXVkIjoiMCIsIm5iZiI6MTY3NzEwNTM4NywiaWF0IjoxNjc3MTA1Mzg3LCJqdGkiOiIyNTc3Iiwic3ViIjoiMzM3NzE3OSJ9.hKKG2spautpVEPTxSR3s-1YtQZ_yY7mNc4YDMpisopxWjI-8YFNNdkhETrjXPzSaOLITqMWZbQw0rz_N3SFqQgFDVwVt5_nzXcFgUYFfJub4gJ7b1zPXB9GAMBMgipdFkDMPUaXHe6KKBaZxPfOMuesYxzNby1Puw3y5O-_waqX5GeFWU6a5X7Kom2RDALxG25w0M014Pj6HPK2qz7ZCVgEFpH0Jaof2gSEJeY5KIcGgjoXAF5yEaEB3Y5EzKqFETIsi6WttT9AQGgyXPd7ppl_mUy1W40vE0nDF2QgdWNCyf8JrT89CbD7jnTYmrx7UsZKBahwvJliCVlxZgJhhhQ")
```

```{r}
# Pull data
# NOTE: Update file permissions for Synapse cache
entity <- synGet("syn51118419", downloadLocation = "../data/")
```

```{r}
# TODO: Push example
```